This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make RM2CPC"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

If you have exported custom behaviors, check the /data/ folder for exported custom behaviors with labels, and associated disassembled functions with matching labels.
These are provided for reference only, they must be manually integrated into the repo.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************

Objects without references must have behaviors created for them, be given an existing behavior, or be commented out.

 Level rr Area 1 has object  Bhv_Custom_0x13003cd4 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003cfc with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003ae8 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003d10 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003d24 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003d54 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003d78 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003df0 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003e10 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003e28 with no known label.
 Level rr Area 1 has object  Bhv_Custom_0x13003f44 with no known label.
 Level rr Area 2 has object  Bhv_Custom_0x13003d8c with no known label.
 Level rr Area 2 has object  Bhv_Custom_0x13003f64 with no known label.

Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.INC.C
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SKYBOXES, THEN SEQUENCES
*****************************************************************************
N64 BUILD
IF SURFACE NODE POOOL OR SURFACE POOL FULL - ADD MORE TRIS TO EXT BOUNDS.H
IF CRASH ON STAR SELECT - PUSH FORWARD GODDARD SEGMENT IN SEGMENTS.H
*****************************************************************************

MORE ON AUDIO ERRORS:
On N64 build, a lack of proper audio memory allocation will instantly crash the game. If this happens, extend gAudioHeap in buffers.c
If you have issues with certain m64s sounding garbled, extend gAlBankSets in load.c (line 2000 about).
If sound cuts out at certain points, extend values in gAudioSessionPresets.
On all builds, if an out of bounds array access happens (often with high sequence numbers) the game will crash or have audio issues.
